---
- include: jdk5.yml
  sudo: yes
  when: java_version is defined and java_version == 1.5

- include: jdkgt5.yml
  sudo: yes
  when: java_version is defined and java_version == 1.7

- name: set JAVA_HOME
  lineinfile: dest={{ansible_env.HOME}}/.bash_profile regexp='^JAVA_HOME' insertbefore='^export' line='JAVA_HOME={{java_home}}'

- name: comment JAVA_HOME
  lineinfile: dest={{ansible_env.HOME}}/.bash_profile regexp='^# JAVA_HOME' insertbefore='^JAVA_HOME' line='# JAVA_HOME (managed by ansible)'

- name: export JAVA_HOME
  lineinfile: dest={{ansible_env.HOME}}/.bash_profile regexp='^export JAVA_HOME' insertafter='^JAVA_HOME' line='export JAVA_HOME\n'